name: 'Cache and get Dependencies'
description: 'Cache and get Dependencies via npm'
inputs:
  caching:
    description: 'whether to cache dependencies or not'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-moduls-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash