name: test-github
on: push

jobs:
    lint-test-and-deploy:
        runs-on: ubuntu-latest
        steps:
         - name: Checkout code
           uses: actions/checkout@v3
         - name: lint
           run: npm lint
         - name: test
           run: npm lint
         - name: deploy
           run: echo "deploying..."

        
