name: deploy-advanced-github 
on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
         - name: Checkout code
           uses: actions/checkout@v3
         - name: Cache dependencies
           id: cache
           uses: actions/cache@v3
           with:
            path: ~/.npm
            key: deps-node-moduls-${{ hashFiles('**/package-lock.json') }}
         - name: Install dependencies
           run: npm ci
         - name: lint
           run: npm run lint
    test:
        continue-on-error: true
        strategy: 
          matrix: 
            node-version: [12, 14, 16]
            operating-system: [ubuntu-latest, windows-latest]
            include: 
              - node-version: 18
                operating-system: macos-latest
        runs-on: ${{ matrix.operating-system }}
        steps:
         - name: Checkout code
           uses: actions/checkout@v3
         - name: Install NodeJS
           uses: actions/setup-node@v3
           with:
            node-version: ${{ matrix.node-version }}
         - name: Cache dependencies
           id: cache
           uses: actions/cache@v3
           with:
            path: ~/.npm
            key: deps-node-moduls-${{ hashFiles('**/package-lock.json') }}
         - name: Install dependencies
           run: npm ci
         - name: test
           continue-on-error: true
           id: test
           run: npm test
         - name: Upload test report
           if: failure() && steps.test.outcome == 'failure'
           uses: actions/upload-artifact@v4.0.0
           with:
            name: test-report
            path: test.json
    build:
        needs: test
        runs-on: ubuntu-latest
        outputs: 
          script-file: ${{ steps.publish.outputs.script-file }}
        steps:
         - name: Checkout code
           uses: actions/checkout@v3
         - name: Cache dependencies
           id: cache
           uses: actions/cache@v3
           with:
            path: ~/.npm
            key: deps-node-moduls-${{ hashFiles('**/package-lock.json') }}
         - name: Install dependencies
           run: npm ci
         - name: Build
           run: npm run build
         - name: Publish JS filename
           id: publish
           run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
         - name: Upload artifact
           uses: actions/upload-artifact@v4.0.0
           with:
            name: dist-files
            path: dist
    deploy:
        needs: build
        uses: ./.github/workflows/reusable.yaml
        with:
           artifact-name: dist-files
           
    report:
      needs: [lint ,deploy]
      if: failure()
      runs-on: ubuntu-latest
      steps:
        - name: Output information
          run: | 
            echo "Something went wrong"
            echo "${{ github }}"
        
